import { expect } from 'chai';
import {
  normalizeTime,
  normalizeObjectTimes,
  normalizeMetricTimes,
  prepareReportResponse,
  getFacet,
} from '../../src/util';

describe('Utils', () => {
  describe('normalizeTime', () => {
    it('should return human readable parsed object', () => {
      const timeInMilliseconds = 1000;
      const expectedOutput = {
        days: 0,
        hours: 0,
        microseconds: 0,
        milliseconds: 0,
        minutes: 0,
        nanoseconds: 0,
        seconds: 1,
      };

      expect(normalizeTime(timeInMilliseconds)).to.be.eql(expectedOutput);
    });

    it('should handle negative time inputs', () => {
      const timeInMilliseconds = -1000;
      const expectedOutput = {
        days: 0,
        hours: 0,
        microseconds: 0,
        milliseconds: 0,
        minutes: 0,
        nanoseconds: 0,
        seconds: 1,
      };

      expect(normalizeTime(timeInMilliseconds)).to.be.eql(expectedOutput);
    });

    it('should handle null value input', () => {
      const expectedOutput = {
        days: 0,
        hours: 0,
        microseconds: 0,
        milliseconds: 0,
        minutes: 0,
        nanoseconds: 0,
        seconds: 0,
      };

      expect(normalizeTime(null)).to.be.eql(expectedOutput);
    });
  });

  describe('normalizeObjectTimes', () => {
    it('should parse object times to human readable times', () => {
      const input = {
        count: 100,
        averageResolveTime: 1000,
        averageAttendTime: 2000,
      };
      const expectedOutput = {
        count: 100,
        averageAttendTime: {
          days: 0,
          hours: 0,
          microseconds: 0,
          milliseconds: 0,
          minutes: 0,
          nanoseconds: 0,
          seconds: 2,
        },
        averageResolveTime: {
          days: 0,
          hours: 0,
          microseconds: 0,
          milliseconds: 0,
          minutes: 0,
          nanoseconds: 0,
          seconds: 1,
        },
      };

      expect(normalizeObjectTimes(input)).to.be.eql(expectedOutput);
    });
  });

  describe('normalizeMetricTimes', () => {
    it('should normalize metrics times and restucture object results', () => {
      const aggregationResult = {
        count: 1,
        pending: 20,
        resolved: 2,
        maximumAssignTime: null,
        minimumAssignTime: null,
        averageAssignTime: null,
        maximumAttendTime: 7813,
        minimumAttendTime: 7813,
        averageAttendTime: 7813,
        maximumCompleteTime: 0,
        minimumCompleteTime: 0,
        averageCompleteTime: 0,
        maximumVerifyTime: 0,
        minimumVerifyTime: 0,
        averageVerifyTime: 0,
        maximumApproveTime: 0,
        minimumApproveTime: 0,
        averageApproveTime: 0,
        maximumResolveTime: 79624349,
        minimumResolveTime: 18750,
        averageResolveTime: 29821770.333333332,
        maximumLateTime: 72424414,
        minimumLateTime: 72424414,
        averageLateTime: 72424414,
        maximumConfirmTime: 7199946,
        minimumConfirmTime: 7199946,
        averageConfirmTime: 7199946,
        maximumCallTime: 0,
        minimumCallTime: 0,
        averageCallTime: 0,
        maximumWorkTime: 0,
        minimumWorkTime: 0,
        averageWorkTime: 0,
      };

      const expectedOutput = {
        approveTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
        },
        assignTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
        },
        attendTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 813,
            minutes: 0,
            nanoseconds: 0,
            seconds: 7,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 813,
            minutes: 0,
            nanoseconds: 0,
            seconds: 7,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 813,
            minutes: 0,
            nanoseconds: 0,
            seconds: 7,
          },
        },
        completeTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
        },
        confirmTime: {
          average: {
            days: 0,
            hours: 1,
            microseconds: 0,
            milliseconds: 946,
            minutes: 59,
            nanoseconds: 0,
            seconds: 59,
          },
          maximum: {
            days: 0,
            hours: 1,
            microseconds: 0,
            milliseconds: 946,
            minutes: 59,
            nanoseconds: 0,
            seconds: 59,
          },
          minimum: {
            days: 0,
            hours: 1,
            microseconds: 0,
            milliseconds: 946,
            minutes: 59,
            nanoseconds: 0,
            seconds: 59,
          },
        },
        count: 1,
        lateTime: {
          average: {
            days: 0,
            hours: 20,
            microseconds: 0,
            milliseconds: 414,
            minutes: 7,
            nanoseconds: 0,
            seconds: 4,
          },
          maximum: {
            days: 0,
            hours: 20,
            microseconds: 0,
            milliseconds: 414,
            minutes: 7,
            nanoseconds: 0,
            seconds: 4,
          },
          minimum: {
            days: 0,
            hours: 20,
            microseconds: 0,
            milliseconds: 414,
            minutes: 7,
            nanoseconds: 0,
            seconds: 4,
          },
        },
        pending: 20,
        resolveTime: {
          average: {
            days: 0,
            hours: 8,
            microseconds: 333,
            milliseconds: 770,
            minutes: 17,
            nanoseconds: 333,
            seconds: 1,
          },
          maximum: {
            days: 0,
            hours: 22,
            microseconds: 0,
            milliseconds: 349,
            minutes: 7,
            nanoseconds: 0,
            seconds: 4,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 750,
            minutes: 0,
            nanoseconds: 0,
            seconds: 18,
          },
        },
        verifyTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
        },
        callTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
        },
        workTime: {
          average: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          maximum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
          minimum: {
            days: 0,
            hours: 0,
            microseconds: 0,
            milliseconds: 0,
            minutes: 0,
            nanoseconds: 0,
            seconds: 0,
          },
        },
        resolved: 2,
      };

      expect(normalizeMetricTimes(aggregationResult)).to.be.eql(expectedOutput);
    });
  });

  describe('prepareReportResponse', () => {
    it('should normalize aggregration results to response format', () => {
      const aggregrationResults = [
        {
          overall: [
            {
              count: 1,
              pending: 20,
              resolved: 10,
              maximumAssignTime: null,
              minimumAssignTime: null,
              averageAssignTime: null,
              maximumAttendTime: 7813,
              minimumAttendTime: 7813,
              averageAttendTime: 7813,
              maximumCompleteTime: 0,
              minimumCompleteTime: 0,
              averageCompleteTime: 0,
              maximumVerifyTime: 0,
              minimumVerifyTime: 0,
              averageVerifyTime: 0,
              maximumApproveTime: 0,
              minimumApproveTime: 0,
              averageApproveTime: 0,
              maximumResolveTime: 79624349,
              minimumResolveTime: 18750,
              averageResolveTime: 29821770.333333332,
              maximumLateTime: 72424414,
              minimumLateTime: 72424414,
              averageLateTime: 72424414,
              maximumConfirmTime: 7199946,
              minimumConfirmTime: 7199946,
              averageConfirmTime: 7199946,
              maximumCallTime: 0,
              minimumCallTime: 0,
              averageCallTime: 0,
              maximumWorkTime: null,
              minimumWorkTime: null,
              averageWorkTime: null,
            },
          ],
          jurisdictions: [
            {
              count: 1,
              name: 'Area',
              pending: 20,
              resolved: 10,
              maximumAssignTime: null,
              minimumAssignTime: null,
              averageAssignTime: null,
              maximumAttendTime: 7813,
              minimumAttendTime: 7813,
              averageAttendTime: 7813,
              maximumCompleteTime: 0,
              minimumCompleteTime: 0,
              averageCompleteTime: 0,
              maximumVerifyTime: 0,
              minimumVerifyTime: 0,
              averageVerifyTime: 0,
              maximumApproveTime: 0,
              minimumApproveTime: 0,
              averageApproveTime: 0,
              maximumResolveTime: 79624349,
              minimumResolveTime: 18750,
              averageResolveTime: 29821770.333333332,
              maximumLateTime: 72424414,
              minimumLateTime: 72424414,
              averageLateTime: 72424414,
              maximumConfirmTime: 7199946,
              minimumConfirmTime: 7199946,
              averageConfirmTime: 7199946,
            },
          ],
          workspaces: [{ name: 'Call', count: 1 }],
        },
      ];

      const expectedOutput = {
        data: {
          overall: {
            resolved: 10,
            approveTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
            },
            assignTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
            },
            attendTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 813,
                minutes: 0,
                nanoseconds: 0,
                seconds: 7,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 813,
                minutes: 0,
                nanoseconds: 0,
                seconds: 7,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 813,
                minutes: 0,
                nanoseconds: 0,
                seconds: 7,
              },
            },
            completeTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
            },
            confirmTime: {
              average: {
                days: 0,
                hours: 1,
                microseconds: 0,
                milliseconds: 946,
                minutes: 59,
                nanoseconds: 0,
                seconds: 59,
              },
              maximum: {
                days: 0,
                hours: 1,
                microseconds: 0,
                milliseconds: 946,
                minutes: 59,
                nanoseconds: 0,
                seconds: 59,
              },
              minimum: {
                days: 0,
                hours: 1,
                microseconds: 0,
                milliseconds: 946,
                minutes: 59,
                nanoseconds: 0,
                seconds: 59,
              },
            },
            count: 1,
            lateTime: {
              average: {
                days: 0,
                hours: 20,
                microseconds: 0,
                milliseconds: 414,
                minutes: 7,
                nanoseconds: 0,
                seconds: 4,
              },
              maximum: {
                days: 0,
                hours: 20,
                microseconds: 0,
                milliseconds: 414,
                minutes: 7,
                nanoseconds: 0,
                seconds: 4,
              },
              minimum: {
                days: 0,
                hours: 20,
                microseconds: 0,
                milliseconds: 414,
                minutes: 7,
                nanoseconds: 0,
                seconds: 4,
              },
            },
            pending: 20,
            resolveTime: {
              average: {
                days: 0,
                hours: 8,
                microseconds: 333,
                milliseconds: 770,
                minutes: 17,
                nanoseconds: 333,
                seconds: 1,
              },
              maximum: {
                days: 0,
                hours: 22,
                microseconds: 0,
                milliseconds: 349,
                minutes: 7,
                nanoseconds: 0,
                seconds: 4,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 750,
                minutes: 0,
                nanoseconds: 0,
                seconds: 18,
              },
            },
            verifyTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
            },
            callTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
            },
            workTime: {
              average: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              maximum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
              minimum: {
                days: 0,
                hours: 0,
                microseconds: 0,
                milliseconds: 0,
                minutes: 0,
                nanoseconds: 0,
                seconds: 0,
              },
            },
          },
          jurisdictions: [
            {
              count: 1,
              name: 'Area',
              resolved: 10,
              approveTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
              },
              assignTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
              },
              attendTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 813,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 7,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 813,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 7,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 813,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 7,
                },
              },
              completeTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
              },
              confirmTime: {
                average: {
                  days: 0,
                  hours: 1,
                  microseconds: 0,
                  milliseconds: 946,
                  minutes: 59,
                  nanoseconds: 0,
                  seconds: 59,
                },
                maximum: {
                  days: 0,
                  hours: 1,
                  microseconds: 0,
                  milliseconds: 946,
                  minutes: 59,
                  nanoseconds: 0,
                  seconds: 59,
                },
                minimum: {
                  days: 0,
                  hours: 1,
                  microseconds: 0,
                  milliseconds: 946,
                  minutes: 59,
                  nanoseconds: 0,
                  seconds: 59,
                },
              },
              lateTime: {
                average: {
                  days: 0,
                  hours: 20,
                  microseconds: 0,
                  milliseconds: 414,
                  minutes: 7,
                  nanoseconds: 0,
                  seconds: 4,
                },
                maximum: {
                  days: 0,
                  hours: 20,
                  microseconds: 0,
                  milliseconds: 414,
                  minutes: 7,
                  nanoseconds: 0,
                  seconds: 4,
                },
                minimum: {
                  days: 0,
                  hours: 20,
                  microseconds: 0,
                  milliseconds: 414,
                  minutes: 7,
                  nanoseconds: 0,
                  seconds: 4,
                },
              },
              pending: 20,
              resolveTime: {
                average: {
                  days: 0,
                  hours: 8,
                  microseconds: 333,
                  milliseconds: 770,
                  minutes: 17,
                  nanoseconds: 333,
                  seconds: 1,
                },
                maximum: {
                  days: 0,
                  hours: 22,
                  microseconds: 0,
                  milliseconds: 349,
                  minutes: 7,
                  nanoseconds: 0,
                  seconds: 4,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 750,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 18,
                },
              },
              verifyTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
              },
              callTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
              },
              workTime: {
                average: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                maximum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
                minimum: {
                  days: 0,
                  hours: 0,
                  microseconds: 0,
                  milliseconds: 0,
                  minutes: 0,
                  nanoseconds: 0,
                  seconds: 0,
                },
              },
            },
          ],
          workspaces: [{ name: 'Call', count: 1 }],
        },
      };

      expect(prepareReportResponse(aggregrationResults)).to.be.eql(
        expectedOutput
      );
    });
  });

  describe('getFacet', () => {
    const defaultFacet = {
      overall: [{ a: 1 }],
      services: [{ b: 2 }],
    };
    it('should return new facet with only selected keys', () => {
      expect(getFacet(defaultFacet, ['overall'])).to.be.eql({
        overall: [{ a: 1 }],
      });
    });

    it('should return default facet when provided key is not part of default facet', () => {
      expect(getFacet(defaultFacet, ['statuses'])).to.eql(defaultFacet);
    });

    it('should return default facet when no key is provided', () => {
      expect(getFacet(defaultFacet, [])).to.eql(defaultFacet);
    });
  });
});
